[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 1
strip = true

[dependencies]

#16
#urlparse = "0.7.3"

#85
#url = "2.2.2"

# 90
#url_serde = "0.2.0"

#51
#url-parse = "0.5.7"
